### PR TITLE
fix: use gulp-umd instead of buggy globalize

### PR DESCRIPTION
**Pull request by zetlen**
The `globalize.js` file used to export to various module loader environments had some buggy behavior in it, making it incompatible with Webpack in next.js. This replaces the hardcoded `globalize.js` and IIFE wrapper with the standardized UMD wrapper, provided by the `gulp-umd`
plugin.

There is no change in functionality, except that for isomorphic apps, Pressure.js will load, but all its methods will be no-ops.

### CODE REVIEW

**Comment by stuyam** [comment]
@zetlen wow this is awesome 🙌! Really great stuff in here, that UMD package is definitely a big improvement and makes the compilation less fragile so thank you for that!

One request I have is would you mind removing the "iife" dependency from the gulp file and ```package.json``` since it is no longer being used? I would greatly appreciate that 😄

**Comment by stuyam** [comment]
@zetlen just deployed this as v2.0.2, thanks for the contribution! Greatly appreciated.

**Comment by zetlen** [comment]
Hey, I'm sorry it took me a while to respond to this--work has been hectic. Sorry I forgot to remote the old dep, that was sloppy of me. I see you've taken care of it.

Hey, your library is great. I really appreciate you doing the work to normalize this into a clean API. You can see it in action, in my own little way, on my personal website: https://zetlen.github.io

**Comment by stuyam** [comment]
@zetlen that is awesome to hear, love the site, very clever! Again I appreciate the help with that last PR, big help. 

Quick question, would you mind taking a look at this issue, I know that pressure works, but I am not sure why this is the case: https://github.com/stuyam/pressure/issues/53

**Pull request merged**
